const vocabulary = [
    { term:'HTML', definition:'', language:'' },
    { term:'Block-Level Element', definition:'', language:'' },
    { term:'Inline Element', definition:'', language:'' },
    { term:'Void Element', definition:'', language:'' },
    { term:'Attributes', definition:'', language:'' },
    { term:'Nesting Element', definition:'', language:'' },
    { term:'List', definition:'', language:'' },
    { term:'Anchor', definition:'', language:'' },
    { term:'Image', definition:'', language:'' },
    { term:'Forms', definition:'', language:'' },
    { term:'Method', definition:'', language:'' },
    { term:'Action', definition:'', language:'' },
    { term:'Query String', definition:'', language:'' },
    { term:'Submitting', definition:'', language:'' },
    { term:'Inputs', definition:'', language:'' },
    { term:'Text Inputs', definition:'', language:'' },
    { term:'Text Areas', definition:'', language:'' },
    { term:'Checkboxes and Radio Buttons', definition:'', language:'' },
    { term:'Selects', definition:'', language:'' },
    { term:'Hidden Inputs', definition:'', language:'' },
    { term:'Name and Value', definition:'', language:'' },
    { term:'Disabled', definition:'', language:'' },
    { term:'Labels', definition:'', language:'' },
    { term:'CSS', definition:'', language:'' },
    { term:'Element Style Attribute', definition:'', language:'' },
    { term:'Inline/Embedded Stylesheet', definition:'', language:'' },
    { term:'External Stylesheet Comments', definition:'', language:'' },
    { term:'Basic Selectors', definition:'', language:'' },
    { term:'Multiple Selectors', definition:'', language:'' },
    { term:'Descendent Selector', definition:'', language:'' },
    { term:'Direct-Child Selector', definition:'', language:'' },
    { term:'Specificity', definition:'', language:'' },
    { term:'Inheriting Styles', definition:'', language:'' },
    { term:'Box Model', definition:'', language:'' },
    { term:'Floating Elements', definition:'', language:'' },
    { term:'Relative Positioning', definition:'', language:'' },
    { term:'Absolute Positioning', definition:'', language:'' },
    { term:'Fixed Positioning', definition:'', language:'' },
    { term:'JavaScript', definition:'', language:'' },
    { term:'Boolean', definition:'', language:'' },
    { term:'Strings', definition:'', language:'' },
    { term:'Operator', definition:'', language:'' },
    { term:'Logical', definition:'', language:'' },
    { term:'Boolean', definition:'', language:'' },
    { term:'Comparison', definition:'', language:'' },
    { term:'Variable', definition:'', language:'' },
    { term:'Constant', definition:'', language:'' },
    { term:'Use Strict', definition:'', language:'' },
    { term:'Function', definition:'', language:'' },
    { term:'Argument', definition:'', language:'' },
    { term:'Parameter', definition:'', language:'' },
    { term:'Function Scope', definition:'', language:'' },
    { term:'Global Variables', definition:'', language:'' },
    { term:'Local Variables', definition:'', language:'' },
    { term:'Immediately-Invoked Function Expression (IIFE)', definition:'', language:'' },
    { term:'Conditionals', definition:'', language:'' },
    { term:'Unit Test', definition:'', language:'' },
    { term:'Loops', definition:'', language:'' },
    { term:'Arrays', definition:'', language:'' },
    { term:'Objects', definition:'', language:'' },
    { term:'Browser Object Model', definition:'', language:'' },
    { term:'Document Object Model', definition:'', language:'' },
    { term:'jQuery', definition:'', language:'' },
    { term:'Ajax Request', definition:'', language:'' },
    { term:'JavaScript Object Notation (JSON)', definition:'', language:'' },
    { term:'Promises', definition:'', language:'' },
    { term:'RESTful API Requests', definition:'', language:'' },
    { term:'Java', definition:'', language:'' },
    { term:'Components of Java', definition:'', language:'' },
    { term:'Statement', definition:'', language:'' },
    { term:'Data Types', definition:'', language:'' },
    { term:'Casting', definition:'', language:'' },
    { term:'Methods', definition:'', language:'' },
    { term:'Method Overloading', definition:'', language:'' },
    { term:'Recursion', definition:'', language:'' },
    { term:'Class', definition:'', language:'' },
    { term:'Field', definition:'', language:'' },
    { term:'Object', definition:'', language:'' },
    { term:'Instance Field', definition:'', language:'' },
    { term:'Static Field', definition:'', language:'' },
    { term:'Constructor', definition:'', language:'' },
    { term:'Visibility', definition:'', language:'' },
    { term:'Inheritance', definition:'', language:'' },
    { term:'Polymorphism', definition:'', language:'' },
    { term:'Overriding', definition:'', language:'' },
    { term:'Final Keyword', definition:'', language:'' },
    { term:'Abstract Class', definition:'', language:'' },
    { term:'Abstract Method', definition:'', language:'' },
    { term:'Interface', definition:'', language:'' },
    { term:'Collection', definition:'', language:'' },
    { term:'ArrayList', definition:'', language:'' },
    { term:'HashMap', definition:'', language:'' },
    { term:'Annotations', definition:'', language:'' },
    { term:'Exceptions', definition:'', language:'' },
    { term:'File', definition:'', language:'' },
    { term:'Path', definition:'', language:'' },
    { term:'JAR File', definition:'', language:'' },
    { term:'Dependencies', definition:'', language:'' },
    { term:'Maven', definition:'', language:'' },
    { term:'JUnit', definition:'', language:'' },
    { term:'Servlets', definition:'', language:'' },
    { term:'Tomcat', definition:'', language:'' },
    { term:'JSP', definition:'', language:'' },
    { term:'JSTL', definition:'', language:'' },
    { term:'MVC', definition:'', language:'' },
    { term:'Data Access Object (DAO)', definition:'', language:'' },
    { term:'Cookies', definition:'', language:'' },
    { term:'Session', definition:'', language:'' },
    { term:'JDBC', definition:'', language:'' },
    { term:'Hashing', definition:'', language:'' },
    { term:'Encryption', definition:'', language:'' },
    { term:'MySQL', definition:'', language:'' },
    { term:'Query', definition:'', language:'' },
    { term:'Database', definition:'', language:'' },
    { term:'Schema', definition:'', language:'' },
    { term:'Primary Keys', definition:'', language:'' },
    { term:'Foreign Keys', definition:'', language:'' },
    { term:'Join', definition:'', language:'' },
    { term:'Inner Join', definition:'', language:'' },
    { term:'Left Join', definition:'', language:'' },
    { term:'Right Join', definition:'', language:'' },
    { term:'Subqueries', definition:'', language:'' },
    { term:'One-to-Many', definition:'', language:'' },
    { term:'Many-to-Many', definition:'', language:'' },
    { term:'Spring', definition:'', language:'' },
    { term:'Controllers', definition:'', language:'' },
    { term:'Views', definition:'', language:'' },
    { term:'Repository', definition:'', language:'' },
    { term:'JPA', definition:'', language:'' },
    { term:'Dependency Injection', definition:'', language:'' },
    { term:'Relationships', definition:'', language:'' },
    { term:'Form Model Binding', definition:'', language:'' },
    { term:'Services', definition:'', language:'' },
    { term:'Security', definition:'', language:'' },
    { term:'Integration Tests', definition:'', language:'' },
    { term:'CRUD', definition:'', language:'' },
];

function showVocabulary(){
        let html = "";
    vocabulary.forEach((word) => {
        html += '<h3>'+ word.term + '</h3>'
    })
    $('#term').append(html);
}

showVocabulary(vocabulary)